### ISSUE TITLE
new Function in loadRemoteModule cannot work with CSP restrictions

### ISSUE THREAD

**Issue by zhaobaiyu** [Paciolan/remote-module-loader#9]
https://github.com/Paciolan/remote-module-loader/blob/9ce278cfc5f874548879c14cb018c1c08fc87e47/src/lib/loadRemoteModule.js#L25

With [CSP](https://developer.chrome.com/extensions/contentSecurityPolicy) restrictions, we cannot evaluate strings of JavaScript, and `new Function` is disabled, so that **Remote Component** cannot work.

Do we have any alternatives of this line, or any other solutions/suggests.

Thanks!

**Comment by joelnet** [comment]
Right now `@paciolan/remote-module-loader` will not work in a CSP restricted website. Further research on CSP is required and we do not have a solution yet.

Look into Webpack's module federation. It offers similar features https://webpack.js.org/concepts/module-federation.

**Comment by joelnet** [comment]
Closing the issue since CSP cannot not supported as is. A warning has been added to the [README](https://github.com/Paciolan/remote-module-loader#content-security-policy-csp).

[Webpack Module Federation](https://webpack.js.org/concepts/module-federation) has also been added to the README as an [Alternative](https://github.com/Paciolan/remote-module-loader#alternatives).
